language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
env:
  - FLASK=1.0.2
  - FLASK=0.12.4
  - FLASK=0.11.1
  - FLASK=0.10.1
install:
  - pip install Flask==$FLASK
  - pip install -r dev_requirements.txt
script: nosetests
